<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<meta name="theme-color" content="#494f5c">
	<meta name="msapplication-TileColor" content="#494f5c">

<meta itemprop="name" content="O Ranking da FIFA e a Copa do Mundo">
<meta itemprop="description" content="Descubra se o ranking da FIFA possui algum tipo de relação com o resultado da Copa do Mundo">


<meta itemprop="datePublished" content="2018-07-09T22:12:00-03:00" />
<meta itemprop="dateModified" content="2018-07-09T22:12:00-03:00" />
<meta itemprop="wordCount" content="1057">



<meta itemprop="keywords" content="copa da mundo,esporte,futebol,machine learning,regressão," />
<meta property="og:title" content="O Ranking da FIFA e a Copa do Mundo" />
<meta property="og:description" content="Descubra se o ranking da FIFA possui algum tipo de relação com o resultado da Copa do Mundo" />
<meta property="og:type" content="article" />
<meta property="og:url" content="/posts/o-ranking-da-fifa-e-a-copa-do-mundo/" />
<meta property="article:published_time" content="2018-07-09T22:12:00-03:00"/>
<meta property="article:modified_time" content="2018-07-09T22:12:00-03:00"/>
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="O Ranking da FIFA e a Copa do Mundo"/>
<meta name="twitter:description" content="Descubra se o ranking da FIFA possui algum tipo de relação com o resultado da Copa do Mundo"/>

	<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
	<link rel="manifest" href="/site.webmanifest">
	<link rel="mask-icon" href="/safari-pinned-tab.svg" color="">
	<link rel="shortcut icon" href="/favicon.ico">

	<title>O Ranking da FIFA e a Copa do Mundo</title>
	<link rel="stylesheet" href="/css/style.min.2abea836b35631572d081e3a3c4e1ab54d8a33a8d87fa93c9b79831551fd44ce.css" integrity="sha256-Kr6oNrNWMVctCB46PE4atU2KM6jYf6k8m3mDFVH9RM4=">
	
</head>

<body id="page">
	
	<header id="site-header" class="animated slideInUp faster">
		<div class="hdr-wrapper section-inner">
			<div class="hdr-left">
				<div class="site-branding">
					<a href="/">Marcus Nunes&#39; Blog</a>
				</div>
				<nav class="site-nav hide-in-mobile">
					<a href="/posts/">Posts</a>
					<a href="/sobre/">Sobre</a>
					<a href="/ensino/">Ensino</a>
					<a href="/pesquisa/">Pesquisa</a>
					<a href="/shiny/">Shiny</a>
					<a href="/midia/">Mídia</a>
				</nav>
			</div>
			<div class="hdr-right hdr-icons">
				<span class="hdr-social hide-in-mobile"><a href="https://twitter.com/_marcus_nunes_" target="_blank" rel="noopener" title="Twitter"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg></a><a href="https://instagram.com/grandeabobora" target="_blank" rel="noopener" title="Instagram"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.5" y2="6.5"></line></svg></a><a href="https://github.com/mnunes" target="_blank" rel="noopener" title="Github"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg></a><a href="https://pt.stackoverflow.com/users/49033/marcus-nunes" target="_blank" rel="noopener" title="Stackoverflow"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-link"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path></svg></a><a href="http://www.linkedin.com/in/marcusanunes" target="_blank" rel="noopener" title="Linkedin"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-linkedin"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg></a><a href="https://marcusnunes.me/contato" target="_blank" rel="noopener" title="Email"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg></a></span><button id="menu-btn" class="hdr-btn" title="Menu"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg></button>
			</div>
		</div>
	</header>
	<div id="mobile-menu" class="animated fast">
		<ul>
			<li><a href="/posts/">Posts</a></li>
			<li><a href="/sobre/">Sobre</a></li>
			<li><a href="/ensino/">Ensino</a></li>
			<li><a href="/pesquisa/">Pesquisa</a></li>
			<li><a href="/shiny/">Shiny</a></li>
			<li><a href="/midia/">Mídia</a></li>
		</ul>
	</div>


	<main class="site-main section-inner animated fadeIn faster">
		<article class="thin">
			<header class="post-header">
				<div class="post-meta"><span>Jul 9, 2018</span></div>
				<h1>O Ranking da FIFA e a Copa do Mundo</h1>
			</header>
			<div class="content">
				


<div id="resumo" class="section level1">
<h1>Resumo</h1>
<p>O ranking da FIFA não serve para prever a classificação final da Copa do Mundo com acurácia.</p>
</div>
<div id="introdução" class="section level1">
<h1>Introdução</h1>
<p>Previsões são muito difíceis de serem feitas, principalmente a respeito do futuro. Mesmo assim, todos nos atraímos por elas, seja para imaginarmos como estaremos daqui a alguns anos ou para partiipar de bolões da copa.</p>
<p>Pensando nisso, resolvi aplicar alguns modelos de predição às informações fornecidas pelo Ranking da FIFA para verificar se ele é uma boa ferramenta para prever o resultado da Copa do Mundo.</p>
</div>
<div id="ranking-da-fifa" class="section level1">
<h1>Ranking da FIFA</h1>
<p>O Ranking da FIFA é uma ferramenta criada nos anos 90 pela entidade máxima do futebol. Este ranking computa informações a respeito dos resultados dos jogos das seleções mundiais, sejam eles em competições ou amistosos, a fim de estabelecer uma classificação geral para elas.</p>
<p>Note que estabelecer uma classificação geral para todas as seleções do mundo não é uma tarefa fácil. Os países da América do Sul jogam muito entre si, seja durante a Copa América, seja durante as eliminatórias da Copa do Mundo.</p>
<p>É razoável supor que o Brasil, país melhor colocado dentre os sul-americanos durante as eliminatórias, seja equivalente ao melhor time europeu. Mas nas eliminatórias europeias os times são divididos em vários grupos distintos, ao contrário das sul-americanas, que ocorrem em um grupo apenas. Sendo assim, qual seria o melhor time europeu neste contexto? E como se comporta o Chile neste ranking, posto que este país ganhou as Copas América de 2015 e 2016, mas ficou fora da Copa 2018?</p>
<p>É aí que entra o <a href="https://www.fifa.com/fifa-world-ranking/ranking-table/men/">Ranking da FIFA</a>. Publicado desde 1995, ele cruza dados e informações e, assim, estabelece uma classificação mundial de seleções. Supostamente, os times melhor colocados no ranking deveriam estar melhor colocados ao final da Copa.</p>
<p>Mas será que isto acontece na prática?</p>
<p>Para testar esta hipótese, resgatei as informações referentes ao último Ranking da FIFA publicado antes de cada Copa do Mundo de 1998 a 2018. Portanto, foram analisadas seis competições.</p>
<p>Os dados do <a href="https://www.fifa.com/fifa-world-ranking/ranking-table/men/">Ranking da FIFA</a> foram obtidos no site da própria instituição. As classificações finais das Copas do Mundo de 1998 a 2018 foram coletadas a partir da Wikipedia em inglês. Os dados utilizados na análise, bem como o código com a modelagem realizada, estão disponíveis no meu <a href="https://github.com/mnunes/">github</a>.</p>
</div>
<div id="correlações" class="section level1">
<h1>Correlações</h1>
<p>Correlação é uma medida estatística que serve para determinar o quanto uma medida está relacionada com a outra. Quanto mais próxima de 1 esta medida for, mais forte é a correlação positiva entre duas variáveis. Quanto mais próxima de 0 esta medida for, mais fraca é a correlação entre duas variáveis.</p>
<p>Por exemplo, peso e altura estão positivamente correlacionados. Quanto mais alto alguém for, mais pesado este alguém tende a ser. Logicamente, esta relação não é perfeita, pois existem pessoas de mesma altura e pesos diferentes, mas a tendência é que pessoas mais altas sejam mais pesadas.</p>
<p>Por exemplo, peso e altura estão positivamente correlacionados. Quanto mais alto alguém for, mais pesado este alguém tende a ser. Logicamente, esta relação não é perfeita, pois existem pessoas de mesma altura e pesos diferentes, mas a tendência é que pessoas mais altas sejam mais pesadas.</p>
<p>O Ranking da FIFA é uma medida ordinal (ou seja, é feita a partir de uma ordem), ela classifica os times do número 1 ao XXX. Desta forma, faz sentido relacioná-lo com a classificação final da Copa do Mundo, que também é uma medida de ordem. Como analisei apenas os resultados das copas em que haviam Ranking da FIFA disponível, os resultados possíveis para os países participantes variaram entre 1 e 32, pois todas as Copas de 1998 em diante contaram com 32 países.</p>
<p>A primeira tarefa que realizaei foi verificar se havia correlação</p>
<pre><code>## 
##  Kendall&#39;s rank correlation tau
## 
## data:  tabela_completa$Rank and tabela_completa$World_Cup
## z = 5.7744, p-value = 7.722e-09
## alternative hypothesis: true tau is not equal to 0
## sample estimates:
##       tau 
## 0.3138331</code></pre>
<p>De acordo com o resultado acima, a correlação entre o Ranking da FIFA e a classificação final na Copa do Mundo é igual a 0.3138331. Este número está mais próximo de 0 do que de 1, o que indica uma correlação não muito forte.</p>
<p>Mas nes primeira análise eu utilizei os dados de seis Copas do Mundo simultaneamente. É natural esperar que esta correlação seja mais forte em alguns anos do que em outros. Por este motivo, vou calcular novamente a correlação entre as variáveis consideradas, mas desta vez agrupando-as por ano:</p>
<pre><code>##   Year estimate statistic p.value  p.fdr
## 1 1998   0.2702  315.0000  0.0302 0.0454
## 2 2002   0.2379  307.0000  0.0573 0.0573
## 3 2006   0.2614    2.0933  0.0363 0.0454
## 4 2010   0.2863  319.0000  0.0213 0.0454
## 5 2014   0.4597  362.0000  0.0001 0.0007</code></pre>
<p>De fato, alguns anos possuíram correlação mais baixa do que 0.3138 e alguns possuíram correlação mais alta do que este valor. Mesmo assim, 0.4597 como valor para a maior correlação não é algo que poderíamos chamar de empolgante.</p>
<p>Com isto em mente, vamos passar ao ajuste de um modelo, mas sem muitas esperanças de que ele tenha um poder preditivo alto, pois as correlações são baixas.</p>
</div>
<div id="previsões" class="section level1">
<h1>Previsões</h1>
<p>Como estamos trabalhando com dados ordinais, vou utilizar um modelo de regressão logística ordinal. Com ele poderei relacionar as variáveis que desejo, além de criar um <em>intervalo de predição</em> para os resultados obtidos.</p>
<p>Grosso modo, o que o intervalo de predição faz é determinar intervalos nos quais nossas predições podem variar. Em outras palavras, o resultado que procuro obter é algo na linha de “dado que o país é o 7º colocado no Ranking da FIFA, há 95% de probabilidade dele terminar a Copa do Mundo entre a 9ª e 6ª colocação”.</p>
<p>Após rodar o modelo, o resultado obtido com as previsões está no gráfico abaixo:</p>
</div>
<div id="conclusão" class="section level1">
<h1>Conclusão</h1>
<p>Ou seja, o Ranking da FIFA não serve para prever a classificação final da Copa do Mundo. Embora seja possível detectar padrões, como os times mais bem colocados no Ranking da FIFA tendem a ficar mais bem classificados ao final da Copa do Mundo, a variabilidade das previsões é muito grande, tornando a ferramenta pouco útil.</p>
<p>Poranto, continue utilizando o com e velho <em>feeling</em> ao fazer preencher o bolão da Copa do Qatar. Dificilmente a estatística vai te ajudar com esta tarefa.</p>
<p>Os dados utilizados na análise, bem como o código com a modelagem realizada, estão disponíveis no meu <a href="https://github.com/mnunes/">github</a>.</p>
</div>

			</div>
			<hr class="post-end">
			<footer class="post-info">
				<p>
					<svg xmlns="http://www.w3.org/2000/svg" width="2" height="2" viewBox="0 0 2 2" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-tag meta-icon"><path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"></path><line x1="7" y1="7" x2="7" y2="7"></line></svg><span class="tag"><a href="/tags/copa-da-mundo">copa da mundo</a></span><span class="tag"><a href="/tags/esporte">esporte</a></span><span class="tag"><a href="/tags/futebol">futebol</a></span><span class="tag"><a href="/tags/machine-learning">machine learning</a></span><span class="tag"><a href="/tags/regress%C3%A3o">regressão</a></span>
				</p>
				<p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>1057 Words</p>
				<p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>2018-07-09 22:12 -0300</p>
			</footer>
		</article>
		<div class="post-nav thin">
			<a class="next-post" href="/posts/como-detectar-fraudes-com-a-lei-de-benford/">
				<span class="post-nav-label"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>&nbsp;Newer</span><br><span>Como Detectar Fraudes nas Contas dos Deputados Federais Utilizando a Lei de Benford</span>
			</a>
			<a class="prev-post" href="/posts/primeiro-projeto-de-data-science/">
				<span class="post-nav-label">Older&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg></span><br><span>Tutorial: Como Fazer o Seu Primeiro Projeto de Data Science</span>
			</a>
		</div>
		<div id="comments" class="thin">
<div id="disqus_thread"></div>
<script type="application/javascript">
    var disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "marcus-nunes-blog" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
	</main>

	<footer id="site-footer" class="section-inner thin animated fadeIn faster">
		<p>&copy; 2013-2019 <a href="/">Marcus Nunes</a> &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a></p>
		<p>
			Made with <a href="https://gohugo.io/" target="_blank" rel="noopener">Hugo</a> &#183; Theme <a href="https://github.com/Track3/hermit" target="_blank" rel="noopener">Hermit</a> &#183; <a href="/posts/index.xml" target="_blank" title="rss"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-rss"><path d="M4 11a9 9 0 0 1 9 9"></path><path d="M4 4a16 16 0 0 1 16 16"></path><circle cx="5" cy="19" r="1"></circle></svg></a>
		</p>
	</footer>


	<script src="/js/main.min.784417f5847151f848c339cf0acb13a06cbb648b1483435a28ed4556c4ead69b.js" integrity="sha256-eEQX9YRxUfhIwznPCssToGy7ZIsUg0NaKO1FVsTq1ps="></script>
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-201649-7', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>


</body>

</html>
