---
title: "Nomes dos Números: Uma Visualização"
description: "Conte o número de letras nos números por extenso e veja onde vamos parar"
tags: ["grafos", "linguística", "números", "visualização"]
draft: false
date: 2018-07-27T13:12:00-03:00
---

Imagine o seguinte procedimento:

1. Sorteie um número entre 1 e 100

2. Escreva este número por extenso

3. Conte o número de caracteres sem espaço obtidos

4. Represente numericamente este resultado

5. Repita os passos de 2 a 4 até os números começarem a se repetir

Seja, por exemplo, o número 40. Se escrevermos 40 por extenso, temos a palavra quarenta. Se contarmos o número de letras de quarenta, obtemos 8. 8 se escreve oito, que possui 4 caractesres. 4 se escreve como quatro, que possui 6 caracteres. 6 é seis e aí o algoritmo termina.

Se repetirmos isto para todos os números de 1 a 100, obtemos a imagem abaixo:

```{r message=FALSE, echo=FALSE}
library(igraph)

numeros <- as.character(read.csv(file="~/Documents/Research/github/numeros/numeros.txt", header=FALSE)[, 1])

numeros <- numeros[1:100]
numeros <- nchar(gsub(" ", "", numeros))

matriz <- matrix(0, ncol=length(numeros), nrow=length(numeros))

for (j in 1:nrow(matriz)) {
  matriz[j, numeros[j]] <- 1
}

grafo <- graph_from_adjacency_matrix(matriz)

par(mar=c(0,0,0,0), mai=c(0,0,0,0))

plot(grafo, edge.arrow.size=0.3, vertex.size=10, vertex.label.cex=0.7, curved=FALSE)
```

Tente encontrar o número 40 no grafo acima e percorra o caminho descrito no parágrafo anterior.

Perceba que há dois grupos de nomes de números que não conversam entre si. Um dos grupos é formado por aqueles números que ao final do algoritmo ficam alternando entre 6 e 4, como no exemplo acima. 

Também há aqueles números que chegam em 5 e por lá ficam.

Também perceba como os números se organizam em torno de alguns valores especiais, como 9, 12, 14, 11, 10 e 13, e partir disso vão para um dos seus destinos finais.

Mas este grafo foi gerado apenas para os números entre 1 e 100. Será que este resultado obtido vale para todos os números? Isto é, se eu tivesse escolhido um valor mais alto, como 4.232.121.935, eu também teria chegado em 4, 6 ou 5 ao repetir este procediento?

Os arquivos utilizados nesta análise podem ser encontrados no [github](https://github.com/mnunes/numeros/). Pegue-os e tente fazer a sua própria visualização.

